SCR_MissionHeader {
 World "{DD28B4CB5145AF0E}Worlds/Kara/PvP_Bunkers_Everon/PvP_Bunkers_Everon.ent"
 m_sName "10 рота"
 m_sAuthor "Kara_Saints"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
 m_sSaveFileName "Tutorial"
}