SCR_MissionHeader {
 World "{38DCC3E614BFA033}Worlds/Kara/PvP_Sturm_Zarichne/PvP_Sturm_Zarichne.ent"
 m_sName "В тесках"
 m_sAuthor "Kara_Saints"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
 m_sSaveFileName "Tutorial"
}