SCR_MissionHeader {
 World "{9F7889CBA09F1532}Worlds/Kara/PvP_Defence_Kolguyev/PvP_Defence_Kolguyev.ent"
 m_sName "Серьёзная угроза"
 m_sAuthor "Kara_Saints"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}