SCR_MissionHeader {
 World "{23520A3AF518F3E2}Worlds/Kara/PvP_Rebel_Takistan/PvP_Rebel_Takistan.ent"
 m_sName "Rebel"
 m_sAuthor "Kara_Saints"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
 m_sSaveFileName "Tutorial"
}