SCR_MissionHeader {
 World "{7D3E5294942A4D8F}Worlds/Kara/Pvp_Defense_Marvinka/Pvp_Defense_Marvinka.ent"
 m_sName "Защита производства"
 m_sAuthor "Kara_Saints"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
 m_sSaveFileName "Tutorial"
}