SCR_MissionHeader {
 World "{B337777E18E4126F}Worlds/Kara/PvP_Grad_Ruha/PvP_Grad_Ruha.ent"
 m_sName "Ужас с небес"
 m_sAuthor "Kara_Saints"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
 m_sSaveFileName "Tutorial"
}