SCR_MissionHeader {
 World "{4F822D8DD29ADB3E}Worlds/Kara/PvP_Three_Targets_Anizay/PvP_Three_Targets_Anizay.ent"
 m_sName "Three Targets"
 m_sAuthor "Kara_Saints"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}