SCR_MissionHeader {
 World "{9A037D3A6248DF78}Worlds/Kara/PvP_Defense_Denali/PvP_Defense_Denali.ent"
 m_sName "Осада замка"
 m_sAuthor "Kara_Saints"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
 m_sSaveFileName "Tutorial"
}