SCR_MissionHeader {
 World "{B39AB2F86B76CA1C}Worlds/Kara/Campain_Barbara/Day_2/PvP_Barbara_1_1_Kolguyev/PvP_Barbara_1_1_Kolguyev.ent"
 m_sName "Операция \"Барбара\". День третий"
 m_sAuthor "Kara_Saints"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}