SCR_MissionHeader {
 World "{C520E7DCEFB5403D}Worlds/Kara/PvP_Piramida_Anizai/PvP_Piramida_Anizai.ent"
 m_sName "Охрана гробницы"
 m_sAuthor "Kara_Saints"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
 m_sSaveFileName "Tutorial"
}