SCR_MissionHeader {
 World "{1DA25E75AFFC2179}Worlds/Kara/PvP_Liberation_Anizay/PvP_Liberation_Anizay.ent"
 m_sName "Liberation"
 m_sAuthor "Kara_Saints"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}