SCR_MissionHeader {
 World "{B890A7ECFA6BB36F}Worlds/Kara/PvP_Piramida_Day_Anizay/PvP_Piramida_Day_Anizay.ent"
 m_sName "Охрана гробницы"
 m_sAuthor "Kara_Saints"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}