SCR_MissionHeader {
 World "{9614A8C0A376661B}Worlds/Kara/PvP_Two_Flags_Arland/PvP_Two_Flags_Arland.ent"
 m_sName "История"
 m_sAuthor "Kara_Saints"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}