SCR_MissionHeader {
 World "{363349ED9F146673}Worlds/Kara/PvP_Bandits_Hamland/PvP_Bandits_Hamland.ent"
 m_sName "Наказание виновных"
 m_sAuthor "Kara_Saints"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
 m_sSaveFileName "Tutorial"
}