SCR_MissionHeader {
 World "{59B7686F55ADA7AB}Worlds/Kara/PvP_DM_Takistan/PvP_DM_Takistan.ent"
 m_sName "Бей и беги"
 m_sAuthor "Kara_Saints"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
 m_sSaveFileName "Tutorial"
}