SCR_MissionHeader {
 World "{D2D8E70CF6D015B2}Worlds/Kara/PvP_Power_Kolguyev/PvP_Power_Kolguyev.ent"
 m_sName "Световая атака"
 m_sAuthor "Kara_Saints"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}