StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{66E0350F923FD82D}" {
   Id "Podval_NSV_AG"
   Target_en_us "Assistant Gunner"
   Target_ru_ru "Помощник наводчика"
   Modified 1726420109
   Author "Biryuk"
   LastChanged "Biryuk"
  }
  CustomStringTableItem "{66E0350FB0C372D1}" {
   Id "Podval_NSV_AMMO"
   Target_en_us "Ammunition carrie"
   Target_ru_ru "Поднощик боеприпасов"
   Modified 1726420113
   Author "Biryuk"
   LastChanged "Biryuk"
  }
  CustomStringTableItem "{66E0350FB911501A}" {
   Id "Podval_NSV_GUNNER"
   Target_en_us "Gunner"
   Target_ru_ru "Наводчик"
   Modified 1726420118
   Author "Biryuk"
   LastChanged "Biryuk"
  }
  CustomStringTableItem "{66E0350FAE942352}" {
   Id "Podval_NSV_SL"
   Target_en_us "Squad leader"
   Target_ru_ru "Начальник пулемёта"
   Modified 1726422203
   Author "Biryuk"
   LastChanged "Biryuk"
  }
  CustomStringTableItem "{66E0350F7D9885C5}" {
   Id "Podval_NSVTeam"
   Target_en_us "NSV Team"
   Target_ru_ru "Расчет НСВ"
   Modified 1726420105
   Author "Biryuk"
   LastChanged "Biryuk"
  }
 }
}