SCR_MissionHeader {
 World "{7DE64CA4F8998A7C}Worlds/Gubastus/TvT_GhostsOfHamertin_Kolguyev/TvT_GhostsOfHamertin_Kolguyev.ent"
 m_sName "Призраки Хамертина"
 m_sAuthor "Gubastus"
 m_sDetails "Podval event"
 m_sIcon "{6CFADAEE9287D1D2}UI/Textures/MissionThumbnails/Default.edds"
 m_sGameMode "TvT"
 m_iPlayerCount 128
}