SCR_MissionHeader {
 World "{17D3ED698AC4A045}Worlds/Gubastus/TvT_GhostsOfMeglerone_Kolguyev/TvT_GhostsOfMeglerone_Kolguyev.ent"
 m_sName "Призраки Меглерона"
 m_sAuthor "Gubastus"
 m_sDetails "Podval event"
 m_sIcon "{6CFADAEE9287D1D2}UI/Textures/MissionThumbnails/Default.edds"
 m_sGameMode "TvT"
 m_iPlayerCount 128
}