SCR_MissionHeader {
 World "{C177F3301105356D}Worlds/Gubastus/TvT_BattleForZargabad_Zargabad/TvT_BattleForZargabad_Zargabad.ent"
 m_sName "Битва за Заргабад"
 m_sAuthor "Gubastus"
 m_sDetails "Podval event"
 m_sIcon "{6CFADAEE9287D1D2}UI/Textures/MissionThumbnails/Default.edds"
 m_sGameMode "TvT"
 m_iPlayerCount 128
}