SCR_MissionHeader {
 World "{31696D211F35417D}Worlds/DimOchka/PvP_TheDefector_Gogland/PvP_TheDefector_Gogland_V2.ent"
 m_sName "Перебежчик"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}