SCR_MissionHeader {
 World "{7E0236502DEEC0D0}Worlds/DimOchka/PvP_SecretData_Anizay/PvP_SecretData_Anizay.ent"
 m_sName "Секретная информация"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}