SCR_MissionHeader {
 World "{C0900BCDDC469BA4}Worlds/Missions/PvP_Blackout_Novka/PvP_Blackout_Novka.ent"
 m_sName "Aurora Borealis"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}