SCR_MissionHeader {
 World "{B40CB47B21AEB6D7}Worlds/DimOchka/PvP_PersonaNonGrata_Fallujah/PvP_PersonaNonGrata_Fallujah.ent"
 m_sName "Персона нон грата"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}