SCR_MissionHeader {
 World "{F443BAB2EC8F57E7}Worlds/Missions/PvP_DnevnoyDozor_Ruha/PvP_DnevnoyDozor_Ruha.ent"
 m_sName "Дневной дозор"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}