SCR_MissionHeader {
 World "{7C9732AAC1B5ED3C}Worlds/Missions/PvP_Kolguev85_Cain/PvP_Kolguev85_Cain.ent"
 m_sName "Колгуев-85"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}