SCR_MissionHeader {
 World "{37E2634D2B8DACB0}Worlds/DimOchka/PvP_Resistance_Bystrany/PvP_Resistance_Bystrany.ent"
 m_sName "Сопротивление"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}