SCR_MissionHeader {
 World "{8463A0E315BED81E}Worlds/DimOchka/PvP_Rangers_Zargabad/PvP_Rangers_Zargabad.ent"
 m_sName "Рейнджеры"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}