SCR_MissionHeader {
 World "{14B16D362ADB4212}Worlds/DimOchka/PvP_WaterProcedure_Bystrany/PvP_WaterProcedure_Bystrany.ent"
 m_sName "Водные процедуры"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}