SCR_MissionHeader {
 World "{96B9804B71EACA3D}Worlds/Missions/PvP_Numbers_Cain/PvP_Numbers_Cain.ent"
 m_sName "Числа"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}