SCR_MissionHeader {
 World "{1839F45B3DB98DFA}Worlds/Missions/PvP_Peacekeepers_Ruha/PvP_Peacekeepers_Ruha.ent"
 m_sName "Миротворцы"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}