SCR_MissionHeader {
 World "{FE51142AE9E284D8}Worlds/DimOchka/PvP_Dune_Modern_Anizay/PvP_Dune_Modern_Anizay.ent"
 m_sName "Дюна"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}