SCR_MissionHeader {
 World "{894460A583FE369B}Worlds/Missions/PvP_EmergencySituation_Navka/PvP_EmergencySituation_Navka.ent"
 m_sName "Чрезвычайная ситуация"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}