SCR_MissionHeader {
 World "{881443581DCA70A7}Worlds/Missions/PvP_StrikeBack_Gogland/PvP_StrikeBack_Gogland.ent"
 m_sName "Ответный удар"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}