SCR_MissionHeader {
 World "{65350844BD8AE4BD}Worlds/Missions/PvP_Dune_Anizay/PvP_Dune_Anizay.ent"
 m_sName "Дюна"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}