SCR_MissionHeader {
 World "{300FC26415E503F9}Worlds/DimOchka/PvP_TheDefector_Gogland/PvP_TheDefector_Gogland.ent"
 m_sName "Перебежчик"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}