SCR_MissionHeader {
 World "{66E16568A55B7F40}Worlds/Gubastus/TvT_SeljukDefence_Kunar/TvT_SeljukDefence_Kunar.ent"
 m_sName "Оборона Селюка"
 m_sAuthor "Gubastus"
 m_sDetails "Podval event"
 m_sIcon "{6136BFC266B2FAAA}Images/podval_img.edds"
 m_sLoadingScreen "{6136BFC266B2FAAA}Images/podval_img.edds"
 m_sPreviewImage "{6136BFC266B2FAAA}Images/podval_img.edds"
 m_sGameMode "TvT"
 m_iPlayerCount 128
}