SCR_MissionHeader {
 World "{FFEC0DCA4AE65137}Worlds/Gubastus/TvT_ApocalypseNow_Vietnam/TvT_ApocalypseNow_Vietnam.ent"
 m_sName "Апокалипсис сегодня"
 m_sAuthor "Gubastus"
 m_sDetails "Podval event"
 m_sIcon "{6CFADAEE9287D1D2}UI/Textures/MissionThumbnails/Default.edds"
 m_sGameMode "TvT"
 m_iPlayerCount 128
}