SCR_MissionHeader {
 World "{2B97D50EB776C5AF}Worlds/Gubastus/TvT_HeliBoss_Takistan/TvT_HeliBoss_Takistan.ent"
 m_sName "Босс Вертолет"
 m_sAuthor "Gubastus"
 m_sDetails "Podval event"
 m_sIcon "{6CFADAEE9287D1D2}UI/Textures/MissionThumbnails/Default.edds"
 m_sGameMode "TvT"
 m_iPlayerCount 128
}