SCR_MissionHeader {
 World "{809C1C2AD17AD964}Worlds/Gubastus/TvT_GhostsOfBovemont_Kolguyev/TvT_GhostsOfBovemont_Kolguyev.ent"
 m_sName "Призраки Бовемонта"
 m_sAuthor "Gubastus"
 m_sDetails "Podval event"
 m_sIcon "{6CFADAEE9287D1D2}UI/Textures/MissionThumbnails/Default.edds"
 m_sGameMode "TvT"
 m_iPlayerCount 128
}