SCR_MissionHeader {
 World "{1B8CDD97D6CE6681}Worlds/Gubastus/TvT_BloodyMirage_Anizay/TvT_BloodyMirage_Anizay.ent"
 m_sName "Кровавый Мираж"
 m_sAuthor "Gubastus"
 m_sDetails "Podval event"
 m_sIcon "{6CFADAEE9287D1D2}UI/Textures/MissionThumbnails/Default.edds"
 m_sGameMode "TvT"
 m_iPlayerCount 128
}