SCR_MissionHeader {
 World "{DC5D81358B534D14}Worlds/Gubastus/TvT_ApocalypseNow_KhanhTrung/TvT_ApocalypseNow_KhanhTrung.ent"
 m_sName "Апокалипсис сегодня"
 m_sAuthor "Gubastus"
 m_sDetails "Podval event"
 m_sIcon "{6CFADAEE9287D1D2}UI/Textures/MissionThumbnails/Default.edds"
 m_sGameMode "TvT"
 m_iPlayerCount 128
}