SCR_MissionHeader {
 World "{33BA6F8DB9399F4D}Worlds/Gubastus/TvT_NightBlade_Kalguyev/TvT_NightBlade_Kalguyev.ent"
 m_sName "Ночной клинок"
 m_sAuthor "Gubastus"
 m_sDetails "Podval event"
 m_sIcon "{6CFADAEE9287D1D2}UI/Textures/MissionThumbnails/Default.edds"
 m_sGameMode "TvT"
 m_iPlayerCount 128
}