SCR_MissionHeader {
 World "{72762DC5D22BD6B3}Worlds/Gyse/Battle_For_Morton_Everon/Battle_For_Morton_Everon.ent"
 m_sName "Battle_For_Morton_Everon"
 m_sAuthor "Mr.Gyse"
 m_sPath "Missions/Gyse/Battle_For_Morton_Everon.conf"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
 m_sSaveFileName "Tutorial"
}