SCR_MissionHeader {
 World "{57136097DBE7F599}worlds/SP/Tutorial/Tutorial.ent"
 m_sName "#AR-Tutorial_Name"
 m_sAuthor "#AR-Author_BI"
 m_sDescription "#AR-Tutorial_ScenarioDescriptionNew"
 m_sIcon "{25564ACFD87FCDDC}UI/Textures/MissionLoadingScreens/Reforger_TutorialArt_UI.edds"
 m_sLoadingScreen "{25564ACFD87FCDDC}UI/Textures/MissionLoadingScreens/Reforger_TutorialArt_UI.edds"
 m_sPreviewImage "{25564ACFD87FCDDC}UI/Textures/MissionLoadingScreens/Reforger_TutorialArt_UI.edds"
 m_sGameMode "Tutorial"
 m_bIsSavingEnabled 1
 m_sSaveFileName "Tutorial"
 m_iStartingHours 12
}