SCR_MissionHeader {
 World "{71E011E20F321EA9}Worlds/Kara/PvP_Hostage_Gogland/PvP_Hostage_Gogland.ent"
 m_sName "Захват заложников"
 m_sAuthor "Kara_Saints"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
 m_sSaveFileName "Tutorial"
}