SCR_MissionHeader {
 World "{1F1DDFD5AF620A22}Worlds/Kara/PvP_Hell_Cain/PvP_Hell_Cain.ent"
 m_sName "4 базы"
 m_sAuthor "Kara_Saints"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}