SCR_MissionHeader {
 World "{479EC33F756331B5}Worlds/Kara/PvP_Ugledar_Kolguyev/PvP_Ugledar_Kolguyev.ent"
 m_sName "Захват промышленности"
 m_sAuthor "Kara_Saints"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}