SCR_MissionHeader {
 World "{21A91721441027AD}Worlds/Kara/PvP_Power_Novka/PvP_Power_Novka.ent"
 m_sName "Да будет свет"
 m_sAuthor "Kara_Saints"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
 m_sSaveFileName "Tutorial"
}