SCR_MissionHeader {
 World "{6F339FC5E12A3319}Worlds/Kara/PvP_Defense_Kolguyev/PvP_Defense_Kolguyev.ent"
 m_sName "Серьёзная угроза"
 m_sAuthor "Kara_Saints"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}