SCR_MissionHeader {
 World "{6E76B6AA6065DB4B}Worlds/Kara/Campain_Barbara/PvP_Barbara_Kolguyev/PvP_Barbara_Kolguyev.ent"
 m_sName "Операция \"Барбара\". День первый"
 m_sAuthor "Kara_Saints"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}