SCR_MissionHeader {
 World "{430E9A915CA86487}Worlds/Kara/Campain_Barbara/Day_1/PvP_Barbara_0_1_Kolguyev/PvP_Barbara_0_1_Kolguyev.ent"
 m_sName "Операция \"Барбара\". День второй"
 m_sAuthor "Kara_Saints"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}