SCR_MissionHeader {
 World "{420510492E8E50AB}Worlds/roxxana/Ruha/FirstMission/AttackOnVirpimaki.ent"
 m_sName "Атака на Virpimaki"
 m_sAuthor "rackson"
 m_sPath "Missions\roxxana\TvT_PehotniyZames_Ruha.conf"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}