SCR_MissionHeader {
 World "{33A72C6D3B81CBE9}Worlds/roxxana/Gogland/FightNearRiver/TvT_FightNearReaver.ent"
 m_sName "Бой у реки"
 m_sAuthor "rackson"
 m_sPath "Missions/roxxana/TvT_FightNearRiver_Gogland.conf"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}