SCR_MissionHeader {
 World "{D4657348D5106682}Worlds/lenya/doubleAttack_Eden/doubleAttack_Eden.ent"
 m_sName "Двойная Атака"
 m_sAuthor "лёня гагнамстайл"
 m_sPath "Missions/lenya/TVT_DoubleAttack_Everon.conf"
 m_sDescription "помянем младшого"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}