SCR_MissionHeader {
 World "{7FD83BCAE73E413E}Worlds/Peroi/Bystrany/test/test.ent"
 m_sName "test"
 m_sAuthor "test"
 m_sDescription "test"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "tvt"
 m_iPlayerCount 128
}