SCR_MissionHeader {
 World "{83889A779A50A949}Worlds/Missions/PvP_NightDozor_Ruha/PvP_NightDozor_Ruha.ent"
 m_sName "Ночной Дозор"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}