StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{630748C234742FF8}" {
   Id "QRPT-Role_Ammo_Bearer"
   Target_en_us "Ammo Bearer"
   Target_ru_ru "Подносчик боеприпасов"
   Modified 1661468686
   Author "John Doe"
   LastChanged "John Doe"
  }
  CustomStringTableItem "{630748C2DD926825}" {
   Id "QRPT-Role_Assistant_Machine_Gunner"
   Target_en_us "Assistant Machine Gunner"
   Target_ru_ru "Помощник пулемётчика"
   Modified 1661435598
   Author "John Doe"
   LastChanged "John Doe"
  }
  CustomStringTableItem "{630676AD8A3CD8B5}" {
   Id "QRPT-Role_CrewDriver"
   Target_en_us "Crew Driver"
   Target_ru_ru "Механик-водитель"
   Modified 1661368090
   Author "qRupt3d"
   LastChanged "John Doe"
  }
  CustomStringTableItem "{630676ADFE68C06F}" {
   Id "QRPT-Role_CrewGunner"
   Target_en_us "Crew Gunner"
   Target_ru_ru "Наводчик-оператор"
   Modified 1661368135
   Author "qRupt3d"
   LastChanged "John Doe"
  }
  CustomStringTableItem "{630748F0BDFA1E23}" {
   Id "QRPT-Role_Rifleman_AT"
   Target_en_us "Rifleman (AT)"
   Target_ru_ru "Стрелок (M72A3)"
   Modified 1661477243
   Author "John Doe"
   LastChanged "John Doe"
  }
  CustomStringTableItem "{630B051CFDB13F7C}" {
   Id "QRPT-Role_VIP"
   Target_en_us "Chief Commander (VIP)"
   Target_ru_ru "Командир стороны (VIP)"
   Modified 1661668651
   Author "John Doe"
   LastChanged "John Doe"
  }
 }
}