SCR_MissionHeaderCampaign {
 World "{685FEA7ECA1BD172}Worlds/Campain_CTI_RHS_Arland/Campain_CTI_RHS_Arland.ent"
 SystemsConfig "{7C9E720397CC6ACD}Configs/Systems/ConflictSystems.conf"
 m_sName "#AR-Campaign_HQC_ScenarioName_Arland"
 m_sAuthor "#AR-Author_BI"
 m_sDescription "#AR-Campaign_HQC_GamemodeDesc"
 m_sDetails "#AR-Campaign_HQC_Hint_Text"
 m_sIcon "{EB78D30911B8548C}UI/Textures/MissionLoadingScreens/Reforger_HQCArt_Arland_UI.edds"
 m_sLoadingScreen "{EB78D30911B8548C}UI/Textures/MissionLoadingScreens/Reforger_HQCArt_Arland_UI.edds"
 m_sPreviewImage "{EFB12CF35AD81450}UI/Textures/MissionLoadingScreens/Reforger_HQCIcon_Arland_UI.edds"
 m_sGameMode "#AR-Scenario_GameMode_Campaign"
 m_iPlayerCount 64
 m_eEditableGameFlags 6
 m_eDefaultGameFlags 6
 m_bRandomStartingWeather 1
 m_bRandomWeatherChanges 1
 m_bMapMarkerEnableDeleteByAnyone 1
 m_iMapMarkerLimitPerPlayer 15
 m_iControlPointsCap 2
 m_fVictoryTimeout 1500
 m_bCommanderRoleEnabled 1
 m_bEstablishingBasesEnabled 1
 m_bSuppliesAutoRegenerationEnabled 0
}