SCR_MissionHeader {
 World "{66069EA2CC31B40B}Worlds/Replays/BystranyView/BystranyView.ent"
 m_sName "Replay Bystrany"
 m_sAuthor "Gubastus"
 m_sPath "Missions\Bystrany_Replay.conf"
 m_sDescription "Get ready to see amazing replay!"
 m_sIcon "{413367902E70794B}Images/ReplaySmol.edds"
 m_sLoadingScreen "{413367902E70794B}Images/ReplaySmol.edds"
 m_sPreviewImage "{413367902E70794B}Images/ReplaySmol.edds"
 m_sGameMode "Replay"
}