SCR_MissionHeader {
 World "{1A4342FE8243C57F}Worlds/Ryba/Marnivka/Old scores.ent"
 m_sName "Старые счёты"
 m_sAuthor "Ryba"
 m_sPath "Missions/Ryba/TvT_Old_scores_Marnivka.conf"
 m_sDescription "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
 m_bIsSavingEnabled 1
 m_iStartingHours 0
}