SCR_MissionHeader {
 World "{880CE028424C3D15}Worlds/lenya/KarranmannikkoAttack_Ruha/Karanmannikko_Attack_Ruha.ent"
 m_sName "Защита Каранманникко"
 m_sAuthor "Лёня Гагнамстайл"
 m_sPath "Missions/lenya/TVT_KaranmannikkoAttack_Ruha.conf"
 m_sDescription "Hamvee MK19, Ruha"
 m_sDetails "Podval Event, респект старшому"
 m_sGameMode "TvT"
 m_iPlayerCount 128
}