SCR_MissionHeader {
 World "{CFEA7D469E0BA89A}Worlds/RamboKZ/TvT_RevengeUSA_Eden/TvT_RevengeUSA_Eden.ent"
 m_sName "Эхо «Грозного»"
 m_sAuthor "RamboKZ"
 m_sPath "Missions/RamboKZ/TvT_RevengeUSA_Eden.conf"
 m_sDetails "Podval event"
 m_sLoadingScreen "{93E6EEDBCD12CA2F}UI/Textures/MissionLoadingScreens/GM_Eden.edds"
 m_sPreviewImage "{93E6EEDBCD12CA2F}UI/Textures/MissionLoadingScreens/GM_Eden.edds"
 m_sGameMode "TvT"
 m_iPlayerCount 128
 m_iStartingHours 9
}