SCR_MissionHeader {
 World "{125A3385A7BEF7AC}Worlds/RamboKZ/TvT_KamorynBase_Bystrany/TvT_KamorynBase_Bystrany.ent"
 m_sName "Эхо «Kamoryn»"
 m_sAuthor "RamboKZ"
 m_sPath "Missions/RamboKZ/TvT_KamorynBase_Bystrany.conf"
 m_sDetails "Podval event"
 m_sLoadingScreen "{93E6EEDBCD12CA2F}UI/Textures/MissionLoadingScreens/GM_Eden.edds"
 m_sPreviewImage "{93E6EEDBCD12CA2F}UI/Textures/MissionLoadingScreens/GM_Eden.edds"
 m_sGameMode "TvT"
 m_iPlayerCount 128
 m_iStartingHours 9
}